const vegetables = ["broccoli", "garlic", "kale", "cabbage", "chives"];
const searchBtn = document.querySelector("#search");
const input = document.querySelector(".form-control");
const myDiv = document.querySelector(".col-9");
console.log(myDiv);
searchBtn.addEventListener("click", () => {
  for (let i = 0; i < vegetables.length; i++) {
    if (input.value === vegetables[i]) {
      switch (input.value) {
        case "kale":
          myDiv.innerHTML =
            "<h1 class='display-3'>Kale</h1><p>Kale originated in the eastern Mediterranean and Asia Minor, where it wascultivated for food beginning by 2000 BCE at the latest.[3] Curly-leavedvarieties of cabbage already existed along with flat-leaved varieties inGreece in the 4th century BC. These forms, which were referred to by theRomans as Sabellian kale, are considered to be the ancestors of modernkales. The earliest record of cabbages in western Europe is ofhard-heading cabbage in the 13th century.[3] Records in 14th-centuryEngland distinguish between hard-heading cabbage and loose-leaf kale.[3]Russian kale was introduced into Canada, and then into the United States,by Russian traders in the 19th century.[3] USDA botanist David Fairchildis credited with introducing kale (and many other crops) toAmericans,[4][5] having brought it back from Croatia,[5] althoughFairchild himself disliked cabbages, including kale.[5] At the time, kalewas widely grown in Croatia mostly because it was easy to grow andinexpensive, and could desalinate soil.[5] For most of the twentiethcentury, kale was primarily used in the United States for decorativepurposes; it became more popular as an edible vegetable in the 1990s dueto its nutritional value.[5] During World War II, the cultivation of kale(and other vegetables) in the U.K. was encouraged by the Dig for Victorycampaign.[6] The vegetable was easy to grow and provided importantnutrients missing from a diet because of rationing.[7]</p>div class='div-image'><img src='https://specialtyproduce.com/sppics/764.png'/></div>";
          break;
        case "broccoli":
          myDiv.innerHTML =
            "<h1 class='display-3'>Broccoli</h1><p>Kale originated in the eastern Mediterranean and Asia Minor, where it wascultivated for food beginning by 2000 BCE at the latest.[3] Curly-leavedvarieties of cabbage already existed along with flat-leaved varieties inGreece in the 4th century BC. These forms, which were referred to by theRomans as Sabellian kale, are considered to be the ancestors of modernkales. The earliest record of cabbages in western Europe is ofhard-heading cabbage in the 13th century.[3] Records in 14th-centuryEngland distinguish between hard-heading cabbage and loose-leaf kale.[3]Russian kale was introduced into Canada, and then into the United States,by Russian traders in the 19th century.[3] USDA botanist David Fairchildis credited with introducing kale (and many other crops) toAmericans,[4][5] having brought it back from Croatia,[5] althoughFairchild himself disliked cabbages, including kale.[5] At the time, kalewas widely grown in Croatia mostly because it was easy to grow andinexpensive, and could desalinate soil.[5] For most of the twentiethcentury, kale was primarily used in the United States for decorativepurposes; it became more popular as an edible vegetable in the 1990s dueto its nutritional value.[5] During World War II, the cultivation of kale(and other vegetables) in the U.K. was encouraged by the Dig for Victorycampaign.[6] The vegetable was easy to grow and provided importantnutrients missing from a diet because of rationing.[7]</p>div class='div-image'><img src='https://domf5oio6qrcr.cloudfront.net/medialibrary/5390/h1218g16207258089583.jpg'/></div>";
          break;
        case "garlic":
            myDiv.innerHTML = "<h1 class='display-3'>Garlic</h1><p>Kale originated in the eastern Mediterranean and Asia Minor, where it wascultivated for food beginning by 2000 BCE at the latest.[3] Curly-leavedvarieties of cabbage already existed along with flat-leaved varieties inGreece in the 4th century BC. These forms, which were referred to by theRomans as Sabellian kale, are considered to be the ancestors of modernkales. The earliest record of cabbages in western Europe is ofhard-heading cabbage in the 13th century.[3] Records in 14th-centuryEngland distinguish between hard-heading cabbage and loose-leaf kale.[3]Russian kale was introduced into Canada, and then into the United States,by Russian traders in the 19th century.[3] USDA botanist David Fairchildis credited with introducing kale (and many other crops) toAmericans,[4][5] having brought it back from Croatia,[5] althoughFairchild himself disliked cabbages, including kale.[5] At the time, kalewas widely grown in Croatia mostly because it was easy to grow andinexpensive, and could desalinate soil.[5] For most of the twentiethcentury, kale was primarily used in the United States for decorativepurposes; it became more popular as an edible vegetable in the 1990s dueto its nutritional value.[5] During World War II, the cultivation of kale(and other vegetables) in the U.K. was encouraged by the Dig for Victorycampaign.[6] The vegetable was easy to grow and provided importantnutrients missing from a diet because of rationing.[7]</p>div class='div-image'><img src='https://static.india.com/wp-content/uploads/2017/05/Garlic.jpg?impolicy=Medium_Resize&w=1200&h=800'/></div>";

          break;
        case "cabbage":
            myDiv.innerHTML = "<h1 class='display-3'>Cabbage</h1><p>Kale originated in the eastern Mediterranean and Asia Minor, where it wascultivated for food beginning by 2000 BCE at the latest.[3] Curly-leavedvarieties of cabbage already existed along with flat-leaved varieties inGreece in the 4th century BC. These forms, which were referred to by theRomans as Sabellian kale, are considered to be the ancestors of modernkales. The earliest record of cabbages in western Europe is ofhard-heading cabbage in the 13th century.[3] Records in 14th-centuryEngland distinguish between hard-heading cabbage and loose-leaf kale.[3]Russian kale was introduced into Canada, and then into the United States,by Russian traders in the 19th century.[3] USDA botanist David Fairchildis credited with introducing kale (and many other crops) toAmericans,[4][5] having brought it back from Croatia,[5] althoughFairchild himself disliked cabbages, including kale.[5] At the time, kalewas widely grown in Croatia mostly because it was easy to grow andinexpensive, and could desalinate soil.[5] For most of the twentiethcentury, kale was primarily used in the United States for decorativepurposes; it became more popular as an edible vegetable in the 1990s dueto its nutritional value.[5] During World War II, the cultivation of kale(and other vegetables) in the U.K. was encouraged by the Dig for Victorycampaign.[6] The vegetable was easy to grow and provided importantnutrients missing from a diet because of rationing.[7]</p>div class='div-image'><img src='https://specialtyproduce.com/sppics/764.png'/></div>";

          break;
        case "chives":
            myDiv.innerHTML = "<h1 class='display-3'>Chives</h1><p>Kale originated in the eastern Mediterranean and Asia Minor, where it wascultivated for food beginning by 2000 BCE at the latest.[3] Curly-leavedvarieties of cabbage already existed along with flat-leaved varieties inGreece in the 4th century BC. These forms, which were referred to by theRomans as Sabellian kale, are considered to be the ancestors of modernkales. The earliest record of cabbages in western Europe is ofhard-heading cabbage in the 13th century.[3] Records in 14th-centuryEngland distinguish between hard-heading cabbage and loose-leaf kale.[3]Russian kale was introduced into Canada, and then into the United States,by Russian traders in the 19th century.[3] USDA botanist David Fairchildis credited with introducing kale (and many other crops) toAmericans,[4][5] having brought it back from Croatia,[5] althoughFairchild himself disliked cabbages, including kale.[5] At the time, kalewas widely grown in Croatia mostly because it was easy to grow andinexpensive, and could desalinate soil.[5] For most of the twentiethcentury, kale was primarily used in the United States for decorativepurposes; it became more popular as an edible vegetable in the 1990s dueto its nutritional value.[5] During World War II, the cultivation of kale(and other vegetables) in the U.K. was encouraged by the Dig for Victorycampaign.[6] The vegetable was easy to grow and provided importantnutrients missing from a diet because of rationing.[7]</p>div class='div-image'><img src='https://foodsguy.com/wp-content/uploads/2020/03/Chives-vs-Green-Onions.jpg'/></div>";

          break;
      }
    }
  }
});
